print ("Script Sudah di update ke versi 2 ")
print ("Update Tambahan menu crack dari pencarian nama")
print ("silahkan clone ulang / ketik: git pull")
print ("dan nama file sudah diganti jadi mbf.py")
print ("jika sudah clone/git pull ketik aja python mbf.py")
